# Copy this file to create your local configuration
[server]
host = "127.0.0.1"
port = 50051

[providers]
# Get your API key from: https://openweathermap.org/api
openweather_api_key = "your_openweather_api_key_here"
# Get your API key from: https://www.weatherapi.com/
weatherapi_api_key = "your_weatherapi_api_key_here"